# Generated by Django 5.2.4 on 2025-07-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Marketing', 'Marketing'), ('Product', 'Product'), ('Case Study', 'Case Study'), ('Research', 'Research'), ('Promotion', 'Promotion')], default='Not selected', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='platform',
            field=models.CharField(choices=[('LinkedIn', 'LinkedIn'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Twitter', 'Twitter'), ('Blog', 'Blog')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Needs Review', 'Needs Review'), ('Ready to Publish', 'Ready to Publish')], default='Needs Review', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
